# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoutweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('body', models.TextField(blank=True, null=True)),
                ('review_rating', models.IntegerField(default=5)),
                ('frequency_used', models.IntegerField(default=3)),
                ('reason', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'review',
                'verbose_name': 'Review',
            },
        ),
        migrations.CreateModel(
            name='ReviewTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('slug', models.CharField(blank=True, help_text='all lowercase, dashes and no spaces!', max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'review_tag',
                'verbose_name': 'Review Tag',
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='review',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shoutweb.Company'),
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='review_tag_map', null=True, to='shoutweb.ReviewTag'),
        ),
    ]
