    # -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoutweb', '0002_auto_20160708_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('slug', models.CharField(blank=True, help_text='all lowercase, dashes and no spaces!', max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'company_group',
                'verbose_name': 'Company Group',
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='review_tag_map', null=True, to='shoutweb.ReviewTag'),
        ),
        migrations.AddField(
            model_name='company',
            name='groups',
            field=models.ManyToManyField(blank=True, db_table='company_group_map', null=True, to='shoutweb.CompanyGroup'),
        ),
    ]
