# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoutweb', '0003_auto_20160712_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='review_tag_map', null=True, to='shoutweb.ReviewTag'),
        ),
    ]
