# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoutweb', '0005_auto_20160811_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shoutweb.Shouter'),
        ),
    ]
